### ISSUE TITLE
Copy Nova URLs

### ISSUE THREAD

**Issue by sgwilym** [eahanson/copy-path.novaextension#1]
Apparently Nova supports URLs of the following format:

```
nova://open?path=[path]&line=[line]&type=[syntax]
```

It would be great if this extension could produce URLs of that format, in addition to providing raw paths.

**Comment by eahanson** [comment]
Done!

<img width="792" alt="image" src="https://github.com/user-attachments/assets/61bc4581-35ca-463f-9da0-33d598ee18ad">

**Comment by eahanson** [comment]
Shipped version 1.1 of the extension with this feature :)

**Comment by sgwilym** [comment]
Great, thank you!
